#pragma once

namespace Client
{
	enum LEVEL
	{
		LEVEL_LOADING,
		LEVEL_STATIC,
		LEVEL_TITLE,
		LEVEL_LOUNGE,
		LEVEL_GAMEPLAY,
		LEVEL_END
	};

	enum class COLLIDER_OWNER
	{
		PLAYER,
		MONSTER,
		BULLET,
		TYPE_END
	};

	enum class PLAYER_STATE
	{
		BOW_ACTION,				CLAYMORE_COMBO,
		ROLL,					DOWNEDFLOOR,
		DRINK,					EATFAST,
		FALLING,				GAUNTLETS_COMBO,
		GAUNTLETS_PUNCHES,		GET_HIT_FRONT,
		GLAIVE_COMBO,			HAMMER_1STRIKE,
		HAMMER_COMBO,			HORN_BLOW,
		IDLE,					IDLE_CLAYMORE,
		IDLE_GLAIVE,			IDLE_HAMMER,
		IDLE_KATANA,			IDLE_LOOKAROUND,
		JUMP,					LASER_POSE,
		MASTER_PUNCH,			PICKAXE,
		RUN,					RUN_CLAYMORE,
		RUN_GLAIVE,				RUN_HAMMER,
		RUN_KATANA,				SOULKNIFE_STAB,
		STUN,					SWORD_COMBO,
		TELEPORT_INITIATE,		TELEPORT_LANDING,
		WALK,					WALK_CLAYMORE,
		WALK_GLAIVE,			WALK_HAMMER,
		WALK_KATANA,			WHIP_COMBO,
		STATE_END
	};

	enum class ZOMBIE_STATE
	{
		ATTACK,
		GET_HIT_FRONT,
		GET_HIT_LEFT,
		GET_HIT_RIGHT,
		IDLE,
		NOVELTY_SLEEP,
		STUN,
		WALK,
		STATE_END
	};
}